# Generated by Django 4.2 on 2023-10-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
