# Generated by Django 4.2 on 2023-10-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='followers',
            new_name='follower',
        ),
    ]
